

spring:
  application:
    name: config-prod


eureka:
  instance:
    hostname: config-prod-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
