server:
  port: 3344

spring:
  application:
    name: config-dev


eureka:
  instance:
    hostname: config-dev-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
