
spring:
  application:
    name: config-dev

config:
  info: config-dev-1.0-good3.0

eureka:
  instance:
    hostname: config-dev-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
